import { AppLayout } from '@/components/app-layout'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Placeholder',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const links: { label: string; path: string }[] = [
    // More links...
    { label: 'Account', path: '/account' },
  ]
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AppLayout links={links}>{children}</AppLayout>
      </body>
    </html>
  )
}
