import { AppLayout } from '@/components/app-layout'
import { ReactQueryProvider } from '@/components/react-query-provider'
import { CHAIN_CONFIG_DEVNET, CHAIN_CONFIG_LOCAL, CHAIN_CONFIG_TESTNET, SolanaProvider } from '@/solana'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Placeholder',
  description: 'Generated by create-solana-dapp',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const links: { label: string; path: string }[] = [
    // More links...
    { label: 'Account', path: '/account' },
  ]
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ReactQueryProvider>
          <SolanaProvider chains={[CHAIN_CONFIG_DEVNET, CHAIN_CONFIG_LOCAL, CHAIN_CONFIG_TESTNET]}>
            <AppLayout links={links}>{children}</AppLayout>
          </SolanaProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
